const NewsActionTypes = {
    FETCH_NEWS: 'FETCH_NEWS',
    SET_TOP_HEADLINES: 'SET_TOP_HEADLINES',
    SET_SEARCH_ARTICLES: 'SET_SEARCH_ARTICLES',
    SET_ERRORS: 'SET_ERRORS'
}

export default NewsActionTypes;